version: '3'

services:

  mysql:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_DATABASE: 'patient_databse'
      
      MYSQL_USER: 'user'
      
      MYSQL_PASSWORD: 'rootroot'
      
      MYSQL_ROOT_PASSWORD: 'rootroot'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      
volumes:
  my-db: {}
      
